# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TejDemo' do
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TejDemo

  platform :ios, '9.0'
  target 'TejDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TejDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
